Selecting and picking columns from a Dataframe

In [9]:
import pandas as pd
df = pd.DataFrame([['AA', "temp", 1],['BB', "temp", 2],['CC', "temp", 3]], columns = ['name','temp', 'value'])

In [10]:
df

  name  temp  value
0   AA  temp      1
1   BB  temp      2
2   CC  temp      3

In [11]:
df2 = df[["name","temp"]]

In [12]:
df2

  name  temp
0   AA  temp
1   BB  temp
2   CC  temp

In [13]:
df

  name  temp  value
0   AA  temp      1
1   BB  temp      2
2   CC  temp      3