Drop columns or pop columns from a dataframe

In [23]:
import pandas as pd
df = pd.DataFrame([['AA', 1],['BB', 2],['CC', 3]], columns = ['name','value'])

In [24]:
df

  name  value
0   AA      1
1   BB      2
2   CC      3

In [26]:
df.drop('name', axis=1)

   value
0      1
1      2
2      3

In [17]:
df

   value
0      1
1      2
2      3

In [27]:
df = pd.DataFrame([['AA', 1],['BB', 2],['CC', 3]], columns = ['name','value'])

In [28]:
df

  name  value
0   AA      1
1   BB      2
2   CC      3

In [30]:
values = df.pop('name')

In [8]:
df

  name
0   AA
1   BB
2   CC

In [9]:
values

0    1
1    2
2    3
Name: value, dtype: int64